### ISSUE TITLE
Automatically determining API version doesn't work?

### ISSUE THREAD

**Issue by rouge8** [Yelp/docker-custodian#17]
Using the `yelp/docker-custodian` Docker image to run `dcgc`, I get a 404 error that I do not get using the `dnephin/docker-custodian` container:

```console
$ docker run --rm \
>   -v /var/run/docker.sock:/var/run/docker.sock \
>   yelp/docker-custodian \
>   dcgc --max-container-age 24Hours --max-image-age 24Hours
Getting all continers
Traceback (most recent call last):
  File "/usr/bin/dcgc", line 9, in <module>
    load_entry_point('docker-custodian==0.5.0', 'console_scripts', 'dcgc')()
  File "/code/docker_custodian/docker_gc.py", line 176, in main
    cleanup_containers(client, args.max_container_age, args.dry_run)
  File "/code/docker_custodian/docker_gc.py", line 25, in cleanup_containers
    all_containers = get_all_containers(client)
  File "/code/docker_custodian/docker_gc.py", line 59, in get_all_containers
    containers = client.containers(all=True)
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 508, in containers
    res = self._result(self._get(u, params=params), True)
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 93, in _result
    self._raise_for_status(response)
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 89, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 404 Client Error: Not Found ("404 page not found")
```

And here's my Docker info:

```console
$ docker info
Containers: 14
Images: 92
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 120
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.0 (TCL 6.3); master : 7f12e95 - Tue Aug 11 17:55:16 UTC 2015
CPUs: 1
Total Memory: 3.859 GiB
Name: dev
ID: EB7N:R3RB:UJIN:H4HE:FF25:QTJJ:FODY:3EEJ:XV57:VM4Y:KRZI:PUGP
Debug mode (server): true
File Descriptors: 11
Goroutines: 22
System Time: 2015-09-29T18:03:55.558954193Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=vmwarefusion
```

**Comment by dnephin** [comment]
Ah, I think we missed upgrading docker-py as part of the `version=auto` change. oops, I'll open a PR to fix this

**Comment by solarkennedy** [comment]
@dnephin @rouge8 thanks!

**Comment by dnephin** [comment]
@solarkennedy  thanks!

Looks like the image on the hub is now fixed
