### ISSUE TITLE
Error while fetching server API version

### ISSUE THREAD

**Issue by rafaelcapucho** [Yelp/docker-custodian#20]
Hello,

I'm running this docker.json marathon config:
```
{
  "cmd": "while [ true ] ; do dcgc --max-container-age=10m --max-image-age=1d ; sleep 120 ; done",
  "cpus": 0.2,
  "mem": 30,
  "ports": [0],
  "id": "custodian",
  "instances": 1,
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "yelp/docker-custodian",
      "network": "HOST",
      "privileged": true,
      "parameters": [
        { "key": "rm", "value": "true" }
      ]
    }
  },
  "volumes": [
    {
      "containerPath": "/var/run/docker.sock",
      "hostPath": "/var/run/docker.sock",
      "mode": "RO"
    }
  ],
  "constraints": [["hostname","UNIQUE"]]
}
```

Into Mesos logerr I'm getting:
```
I1005 16:37:39.241235   515 exec.cpp:134] Version: 0.26.0
I1005 16:37:39.260869   520 exec.cpp:208] Executor registered on slave 298381af-1519-4de0-87fd-336a076029f5-S20
WARNING: Your kernel does not support swap limit capabilities, memory limited without swap.
Traceback (most recent call last):
  File "/usr/bin/dcgc", line 9, in <module>
    load_entry_point('docker-custodian==0.5.1', 'console_scripts', 'dcgc')()
  File "/code/docker_custodian/docker_gc.py", line 173, in main
    client = docker.Client(version='auto', timeout=args.timeout)
  File "/usr/lib/python2.7/site-packages/docker/clientbase.py", line 54, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/lib/python2.7/site-packages/docker/clientbase.py", line 74, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))
```

If I run directly, it works!:
```
docker pull yelp/docker-custodian
docker run -ti \
    -v /var/run/docker.sock:/var/run/docker.sock \
    yelp/docker-custodian dcgc --help
```

But I would like to run spread of all our mesos slave using marathon.

**Comment by dnephin** [comment]
It sounds like when you're running it on marathon it's not able to connect to the docker daemon.  It's trying to use the default socket, but failing to connect. Is it running on port? or maybe the permissions are wrong?

**Comment by rafaelcapucho** [comment]
@dnephin Thank you, your answer help me find that my volume declaration was outside of container scope, the correct version is:
```
{
  "cmd": "while [ true ] ; do dcgc --max-container-age=10m --max-image-age=1d ; sleep 120 ; done",
  "cpus": 0.2,
  "mem": 30,
  "ports": [0],
  "id": "custodian",
  "instances": 1,
  "constraints": [["hostname","UNIQUE"]],
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "yelp/docker-custodian",
      "network": "HOST",
      "privileged": true,
      "parameters": [
        { "key": "rm", "value": "true" }
      ]
    },
    "volumes": [
      {
        "containerPath": "/var/run/docker.sock",
        "hostPath": "/var/run/docker.sock",
        "mode": "RO"
      }
    ]
  }
}
```
