### ISSUE TITLE
--dangling-volumes runs into an error when there are no dangling volumes

### ISSUE THREAD

**Issue by Bert-R** [Yelp/docker-custodian#41]
I tried running Custodian with the new ``--dangling-volumes`` flag, like this:

```
docker run -i --rm -v /var/run/docker.sock:/var/run/docker.sock yelp/docker-custodian dcgc --dangling-volumes --max-container-age ...
```

But that causes the following error:
```
Getting all containers
Found 11 containers
Getting all containers
Found 11 containers
Getting all images
Found 33 images
Getting dangling volumes
Traceback (most recent call last):
  File "/usr/bin/dcgc", line 9, in <module>
    load_entry_point('docker-custodian==0.7.0', 'console_scripts', 'dcgc')()
  File "/code/docker_custodian/docker_gc.py", line 222, in main
    cleanup_volumes(client, args.dry_run)
  File "/code/docker_custodian/docker_gc.py", line 163, in cleanup_volumes
    dangling_volumes = get_dangling_volumes(client)
  File "/code/docker_custodian/docker_gc.py", line 80, in get_dangling_volumes
    log.info("Found %s dangling volumes", len(volumes))
TypeError: object of type 'NoneType' has no len()
```

This might be because there were no dangling volumes at the time I ran Custodian

**Comment by IamTheFij** [comment]
This looks like it was fixed in #45
